Cache  cleaner  - Delete tegola process after x numbers
developmentseed/osm-seed pull request #298
Opened 2023-08-17 21:22 UTC by Rub21

cc. @batpad

2023-08-18 05:43 UTC, geohacker requested changes
@Rub21 this doesn't look like a great approach to kill tegola processes to make more resources available on the container. We shouldn't arbitrarily kill tegola processes.

Instead, we should improve the tiler resources overall so that it can catchup to edits and tile expiry. Let's not merge this PR. cc @batpad

2023-08-31 21:30 UTC, Rub21 commented
Following my discussion with @batpad, we've decided to proceed with this approach for cleaning the cache, until we find a better solution for handling the cache cleaner. I won't merge this Pull Request just yet; instead, I'll use this Helm template version  to deploy it in both the staging and production environments for OHM.

2023-08-31 21:31 UTC, batpad approved these changes

2023-09-01 19:12 UTC, Rub21 commented
@batpad  In order to implement cgmap, and test I will merge  this PR and the later we can just remove just some configurations about the tiler cache cleaner.

2023-09-01 19:12 UTC, merged